# Generated by Django 5.0 on 2024-02-27 14:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfdriveapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pickdate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='listing date'),
            preserve_default=False,
        ),
    ]
